# Site settings
title: HiAccounting
email: dev@ocupop.com
description: ''
url: "http://client_url"
permalink: /:title

# Build settings
safe: false
source: src
include: ["_pages"]

gems:
  - jekyll-sitemap