# Site settings
title: HiAccounting
email: dev@ocupop.com
description: ''
url: "http://client_url"
permalink: /:title

collections:
  staff:
    output: true
  positions: 
    output: true  
defaults:
  - scope:
      type: staff
    values:
      layout: default
  - scope:
      type: positions
    values: 
      layout: position

# Build settings
safe: false
source: src

gems:
  - jekyll-sitemap