# Site settings
title: HiAccounting
email: dev@ocupop.com
contact_number: 808-529-9990
description: ''
url: "https://hi-accounting.com"
permalink: /:title

press_url: "https://important-chickpea.cloudvent.net"
local_press_url: "/hi-accounting/index.json"

collections:
  staff:
    output: true
  positions:
    output: true
defaults:
  - scope:
      type: staff
    values:
      layout: staff
  - scope:
      type: positions
    values:
      layout: position

# Build settings
safe: false
source: src

gems:
  - jekyll-sitemap