# Site settings
title: HiAccounting
email: dev@ocupop.com
description: ''
url: "http://client_url"
permalink: /:title

press_url: "http://important-chickpea.cloudvent.net"
local_press_url: "/hi-accounting/index.json"

collections:
  staff:
    output: true
  positions: 
    output: true  
defaults:
  - scope:
      type: staff
    values:
      layout: staff
  - scope:
      type: positions
    values: 
      layout: position

# Build settings
safe: false
source: src

gems:
  - jekyll-sitemap