# Site settings
title: HiAccounting
email: dev@ocupop.com
contact_number: 808-529-9990
description: ''
url: "https://hi-accounting.com"
permalink: pretty

press_url: "https://important-chickpea.cloudvent.net"
local_press_url: "/hi-accounting/index.json"

collections:
  staff:
    output: true
  positions:
    output: true
  resources:
    output: true
defaults:
  - scope:
      type: staff
    values:
      layout: staff
  - scope:
      type: positions
    values:
      layout: position
  - scope:
      type: resources
    values:
      layout: resource

announcement_categories:
  - CARES
  - Families First
  - Additional Guidance

# Build settings
safe: false

plugins:
  - jekyll-sitemap
  - jekyll-paginate-v2



